# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Pic',
            field=models.CharField(default='defaultarticle.jpeg', max_length=100),
        ),
    ]
