# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Category',
            field=models.CharField(choices=[('Sciense', 'Sciense'), ('Sport', 'Sport'), ('Economics', 'Economics'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Text',
            field=models.TextField(verbose_name='\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
        ),
    ]
